### ISSUE TITLE
[Feature request] Android user album

### ISSUE THREAD

**Issue by HenrikH96** [fluttercandies/flutter_photo_manager#1041]
### Platforms

Android

### Description

Hello,

I've observed that PhotoManager.getAssetPathList() only retrieves device folders and not the albums created by the user. Is there a method to access user-generated albums as well? I'm currently testing on a Pixel 7.

Thank you for your assistance.

### Why

This feature would be incredibly useful for my diary app, as it would allow users who have already sorted their pictures to easily browse through their pre-made albums.

**Comment by CaiJingLong** [comment]
In Android, MediaStore is retrieved, regardless of whether it was created by a user. As long as you have access permission, you can view it (a limit has been added in Android 14 System api).
In Android, [BUCKET_ID][] in MediaStore is used as the id of PathEntity.

[BUCKET_ID]: https://developer.android.com/reference/android/provider/MediaStore.MediaColumns?hl=en#BUCKET_ID

**Comment by HenrikH96** [comment]
First of all, thank you for your prompt response. However, I'm encountering an issue on my phone, and it might be specific to Google Photos.

When I fetch my albums using the following code:
 `  
 var albumslist = await PhotoManager.getAssetPathList(
      type: RequestType.image,
      filterOption: FilterOptionGroup(
        orders: [
          const OrderOption(type: OrderOptionType.updateDate, asc: false)
        ],
    
      ),
    );
    `
    
    
Certainly! Here's how you can phrase your message in clear and fluent English:

First of all, thank you for your prompt response. However, I'm encountering an issue on my phone, and it might be specific to Google Photos.

When I fetch my albums using the following code:

dart
Copy code
var albumslist = await PhotoManager.getAssetPathList(
  type: RequestType.image,
  filterOption: FilterOptionGroup(
    orders: [
      const OrderOption(type: OrderOptionType.updateDate, asc: false)
    ],
  ),
);
I only receive the device folders (which are marked in red) and not the user-generated folders (which are marked in green).

![Screenshot 2023-11-21 231300](https://github.com/fluttercandies/flutter_photo_manager/assets/47558765/f4675269-ee80-469d-bc35-20706e227c53)

![Screenshot 2023-11-21 231416](https://github.com/fluttercandies/flutter_photo_manager/assets/47558765/4d026297-c6f0-416b-9b69-798df1f1a641)

Could this be a problem specific to how Google "Photos" organizes albums or do i need any extra permission ?

**Comment by CaiJingLong** [comment]
I don't use Google Photos because Google doesn't serve my area. 
But my system album will also provide Smart album, and I guess google photos should be the same.

I can guess that this approach may be similar to the concept of smart photo albums in the iPhone.

It doesn't look like it has anything to do with MediaStore.  The photo_manager just query from MediaStore.

**Comment by CaiJingLong** [comment]
By the way, the smart photo album in the iOS system is provided by the system's photos API, so it can be retrieved and it has a more refined encapsulation.
But Android only provides MediaStore for unified retrieval of resources. Its operation is more like reading a sqlite database (although it is actually a database).

Android's system photo apps can "intelligently identify" photo albums and categorize them. It should be the app itself that has done the categorization. For example, your category that seems to be a location may be because photos have a built-in database for querying locations through the longitude and latitude of images, or the locations obtained by API requests.

**Comment by HenrikH96** [comment]
The "Norway" albums were manually created by me. I made them by clicking the 'New Album' button, naming them, and then adding some pictures. However, I think this highlights one of the drawbacks of Android, where everyone seems to do things their own way.

Thank you so much for your assistance.

Best regards,
Henrik
