### ISSUE TITLE
[Feature] Get the first entity from an album

### ISSUE THREAD

**Issue by bharatmk256** [fluttercandies/flutter_photo_manager#529]
It would be much better if we can get first image of album, as we already listing album title and also count of images/videos in that album

Currently I am using `await albums[0].getAssetListPaged(currentPage, 0);` but it would be much better if it will be built in thing

**Comment by 1AhmedYasser** [comment]
Totally agree

**Comment by AlexV525** [comment]
This is actually a method that would makes side effects.

Considering we have a method like `AssetPathEntity.getTheFirstEntity` that return the first `AssetEntity` in this album. Now if a user is implementing a picker that both show entities list and the first entity's thumbnail, may found this method and use it directly with the list method without hesitation since it's _very useful_.

But the user might never noticed that instead of a separate request, the user can directly use the first entity that returned from the list, which improves the performance in the loading queue.

AFAIK the request of this implementation has less popularity then other regular requests, so I suggest to use APIs as provided currently.

**Comment by AlexV525** [comment]
Closing since we don't have the intention to implement this.
