### ISSUE TITLE
[BUG] Error with permissions and paths

### ISSUE THREAD

**Issue by Miedziaq** [fluttercandies/flutter_photo_manager#690]
**Describe the bug**
Hello, generally your library works well for me, but im stuck into the problem of paths:
from AssetEntity im getting the path on example:   download/picture1.jpg
when im trying to use await http.MultipartFile.fromPath() method using this path provided by your library im geting exception that the length of the file cannot be accesed.

So i tried to File.openRead(path), and unfortunatelly all paths returned by this method is the same....
after i added   '/storage/emulated/0/'  before path it works then....

In tries to fix the problem to get the absolute paths, I tried to add permissions you mentioned in doc:
WRITE_EXTERNAL_STORAGE
READ_EXTERNAL_STORAGE
INTERNET
ACCESS_MEDIA_LOCATION
CAMERA

then after reinstall of application im asked about permissions, I allowed everything im asked and...
to my surprise your library stopped working... im geting the error : StateError (Bad state: Permission state error with PermissionState.denied.)

Do you have any tips or advices on this problem???

**Version information**

- Device: emulator of pixel 4 api 30
- OS: android api 30
- Package Version: 1.3.10
- Flutter Version: 2.8.1

**Comment by AlexV525** [comment]
- I didn't see any useful code (related to this plugin)
- I'm not getting any detailed info
- Relative paths are **relative**, for absolute paths, you must obtain them from files.

Running on Android 30 Emulator:
![image](https://user-images.githubusercontent.com/15884415/150626393-d6db0d8c-181c-4738-8bb3-cbd707b21bd2.png)

Closing, as this issue is missing details and requirements.
